language: node_js
sudo: required

node_js:
  - "10.15.1"

env:
  - CXX=g++-4.8
  - CXX=g++-4.8 KAFKA_URL=kafka://127.0.0.1:9093 KAFKA_CLIENT_CERT="${TRAVIS_BUILD_DIR}/test/testkit/ssl/client.crt" KAFKA_CLIENT_CERT_KEY="${TRAVIS_BUILD_DIR}/test/testkit/ssl/client.key"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    update: true

services:
  - docker

before_install:
  - docker pull spotify/kafka
